// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eRekreacija.Services.Database.Context;

#nullable disable

namespace eRekreacija.Services.Migrations.Rekreacija
{
    [DbContext(typeof(RekreacijaContext))]
    [Migration("20250605173944_changeIdToStringChatMessage")]
    partial class changeIdToStringChatMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Appointment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("appointment_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("end_time")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("is_approved")
                        .HasColumnType("bit");

                    b.Property<int>("object_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("start_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("object_id");

                    b.ToTable("tbl_Appointment", (string)null);
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tbl_ChatMessage", (string)null);
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Favorites", b =>
                {
                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("object_id")
                        .HasColumnType("int");

                    b.Property<int?>("tbl_Objectsid")
                        .HasColumnType("int");

                    b.HasKey("user_id", "object_id");

                    b.HasIndex("object_id");

                    b.HasIndex("tbl_Objectsid");

                    b.ToTable("tbl_Favorites", (string)null);
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Holiday", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("tbl_Holiday", (string)null);
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Notification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tbl_Notification", (string)null);
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_ObjectHoliday", b =>
                {
                    b.Property<int>("object_id")
                        .HasColumnType("int");

                    b.Property<int>("holiday_id")
                        .HasColumnType("int");

                    b.HasKey("object_id", "holiday_id");

                    b.HasIndex("holiday_id");

                    b.ToTable("tbl_ObjectHoliday", (string)null);
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_ObjectSportCategory", b =>
                {
                    b.Property<int>("object_id")
                        .HasColumnType("int");

                    b.Property<int>("sport_category_id")
                        .HasColumnType("int");

                    b.HasKey("object_id", "sport_category_id");

                    b.HasIndex("sport_category_id");

                    b.ToTable("tbl_ObjectSportCategory", (string)null);
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Objects", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tbl_Objects", (string)null);
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Payment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<float>("amount")
                        .HasColumnType("real");

                    b.Property<int>("appointment_id")
                        .HasColumnType("int");

                    b.Property<int>("object_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("paid_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("appointment_id")
                        .IsUnique();

                    b.HasIndex("object_id");

                    b.ToTable("tbl_Payment", (string)null);
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Review", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("object_id")
                        .HasColumnType("int");

                    b.Property<float>("rating")
                        .HasColumnType("real");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("object_id");

                    b.ToTable("tbl_Review", (string)null);
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_SportCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("tbl_SportCategory", (string)null);
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Appointment", b =>
                {
                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Objects", "TblObjects")
                        .WithMany("Appointments")
                        .HasForeignKey("object_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblObjects");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Favorites", b =>
                {
                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Objects", "TblObjects")
                        .WithMany()
                        .HasForeignKey("object_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Objects", null)
                        .WithMany("Favorites")
                        .HasForeignKey("tbl_Objectsid");

                    b.Navigation("TblObjects");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_ObjectHoliday", b =>
                {
                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Holiday", "TblHoliday")
                        .WithMany("ObjectHolidays")
                        .HasForeignKey("holiday_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Objects", "TblObjects")
                        .WithMany("ObjectHoliday")
                        .HasForeignKey("object_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblHoliday");

                    b.Navigation("TblObjects");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_ObjectSportCategory", b =>
                {
                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Objects", "TblObject")
                        .WithMany("ObjectSportCategory")
                        .HasForeignKey("object_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_SportCategory", "TblSportcategory")
                        .WithMany("ObjectSportCategories")
                        .HasForeignKey("sport_category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblObject");

                    b.Navigation("TblSportcategory");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Payment", b =>
                {
                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Appointment", "TblAppointment")
                        .WithOne("TblPayment")
                        .HasForeignKey("eRekreacija.Services.Database.Entities.tbl_Payment", "appointment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Objects", "TblObjects")
                        .WithMany("Payment")
                        .HasForeignKey("object_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TblAppointment");

                    b.Navigation("TblObjects");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Review", b =>
                {
                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Objects", "TblObjects")
                        .WithMany("Reviews")
                        .HasForeignKey("object_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblObjects");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Appointment", b =>
                {
                    b.Navigation("TblPayment")
                        .IsRequired();
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Holiday", b =>
                {
                    b.Navigation("ObjectHolidays");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Objects", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Favorites");

                    b.Navigation("ObjectHoliday");

                    b.Navigation("ObjectSportCategory");

                    b.Navigation("Payment");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_SportCategory", b =>
                {
                    b.Navigation("ObjectSportCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
