networks:
  erekreacijanet:
    driver: bridge 

services:
  # mssql docker
    erekreacija-sql:
        container_name: erekreacija-sql
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: unless-stopped
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=${SQL_PASSWORD}
          - MSSQL_PID=Developer
        ports:
          - ${SQL_PORT}:1433
        expose:
          - 1433
        networks:
          - erekreacijanet

    erekreacija-api:
        restart: unless-stopped
        build:
          context: .
        environment:
          - ConnectionStrings__RekreacijaConnection=Server=${SQL_HOST}, 1433;Database=${SQL_DATABASE};User Id=${SQL_USER};Password=${SQL_PASSWORD};TrustServerCertificate=True
          - ASPNETCORE_ENVIRONMENT=Development
          - RabbitMQ_Host=erekreacija-rabbitmq
          - RabbitMQ_Username=${RABBITMQ_USER} 
          - RabbitMQ_Password=${RABBITMQ_PASSWORD} 
          - RabbitMQ_Virtualhost=/
          - RABBITMQ_PORT=5672
        ports:
          - 7271:7271
        networks:
          - erekreacijanet
        links:
          - erekreacija-sql
        depends_on:
          - erekreacija-sql         

    #RABBIT_MQ
    erekreacija-rabbitmq:
        image: rabbitmq:3.8-management-alpine
        container_name: erekreacija-rabbitmq
        hostname: erekreacija-rabbitmq
        restart: unless-stopped
        ports:
          - 5672:5672  
          #- 8080:15672
          - 15692:15692
        expose:
          - 5672
          - 8080
        environment:
          - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER} 
          - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD} 
        depends_on:
          - erekreacija-api
        networks:
          - erekreacijanet
        volumes:
          - ./docker_data/rabbitmq_data:/var/lib/rabbitmq
          - ./docker_data/rabbitmq_logs:/var/log/rabbitmq
        healthcheck:
          test: ["CMD", "rabbitmqctl", "status"]
          interval: 30s
          timeout: 10s
          retries: 5
          
    erekreacija-mailservice:
        restart: unless-stopped
        container_name: erekreacija-mailservice
        hostname: erekreacija-mailservice
        image: registration-email-consumer:latest
        build: 
            context: .
            dockerfile: RegistrationEmailServiceDockerFile
        environment:
          - RabbitMQ_Host=erekreacija-rabbitmq
          - RabbitMQ_Username=${RABBITMQ_USER} 
          - RabbitMQ_Password=${RABBITMQ_PASSWORD} 
          - RabbitMQ_Virtualhost=/
          - RABBITMQ_PORT=5672
          - Email=${EMAIL_FROM}
          - EmailUsername=${SMTP_USER}
          - Password=${SMTP_PASSWORD}
          - Port=${SMTP_PORT} 
          - Host=${SMTP_HOST}
        # volumes:
        #     - ./appsettings.json:/app/appsettings.json
        depends_on:
              erekreacija-rabbitmq:
                condition: service_healthy
        networks:
           - erekreacijanet
