// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eRekreacija.Services.Database.Context;

#nullable disable

namespace eRekreacija.Services.Migrations
{
    [DbContext(typeof(IdentityContext))]
    [Migration("20250629123406_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", "Identity");

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "Identity");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Appointment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("appointment_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("end_time")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("is_approved")
                        .HasColumnType("bit");

                    b.Property<int?>("number_of_players")
                        .HasColumnType("int");

                    b.Property<int>("object_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("start_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("object_id");

                    b.HasIndex("user_id");

                    b.ToTable("tbl_Appointment", "Identity");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("tbl_ChatMessage", "Identity");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Favorites", b =>
                {
                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("object_id")
                        .HasColumnType("int");

                    b.Property<int?>("tbl_Objectsid")
                        .HasColumnType("int");

                    b.HasKey("user_id", "object_id");

                    b.HasIndex("object_id");

                    b.HasIndex("tbl_Objectsid");

                    b.ToTable("tbl_Favorites", "Identity");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Holiday", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("tbl_Holiday", "Identity");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Notification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("tbl_Notification", "Identity");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_ObjectHoliday", b =>
                {
                    b.Property<int>("object_id")
                        .HasColumnType("int");

                    b.Property<int>("holiday_id")
                        .HasColumnType("int");

                    b.HasKey("object_id", "holiday_id");

                    b.HasIndex("holiday_id");

                    b.ToTable("tbl_ObjectHoliday", "Identity");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_ObjectSportCategory", b =>
                {
                    b.Property<int>("object_id")
                        .HasColumnType("int");

                    b.Property<int>("sport_category_id")
                        .HasColumnType("int");

                    b.HasKey("object_id", "sport_category_id");

                    b.HasIndex("sport_category_id");

                    b.ToTable("tbl_ObjectSportCategory", "Identity");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Objects", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("tbl_Objects", "Identity");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Payment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<float>("amount")
                        .HasColumnType("real");

                    b.Property<int>("appointment_id")
                        .HasColumnType("int");

                    b.Property<int>("object_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("paid_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("appointment_id")
                        .IsUnique();

                    b.HasIndex("object_id");

                    b.HasIndex("user_id");

                    b.ToTable("tbl_Payment", "Identity");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Review", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("object_id")
                        .HasColumnType("int");

                    b.Property<float>("rating")
                        .HasColumnType("real");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("object_id");

                    b.HasIndex("user_id");

                    b.ToTable("tbl_Review", "Identity");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_SportCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("tbl_SportCategory", "Identity");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicutre")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool?>("isApproved")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Appointment", b =>
                {
                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Objects", "TblObjects")
                        .WithMany("Appointments")
                        .HasForeignKey("object_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eRekreacija.Services.Database.ApplicationUser", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TblObjects");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_ChatMessage", b =>
                {
                    b.HasOne("eRekreacija.Services.Database.ApplicationUser", "Recipient")
                        .WithMany("RecievedMessage")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eRekreacija.Services.Database.ApplicationUser", "Sender")
                        .WithMany("SentMessges")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Favorites", b =>
                {
                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Objects", "TblObjects")
                        .WithMany()
                        .HasForeignKey("object_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Objects", null)
                        .WithMany("Favorites")
                        .HasForeignKey("tbl_Objectsid");

                    b.HasOne("eRekreacija.Services.Database.ApplicationUser", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TblObjects");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Notification", b =>
                {
                    b.HasOne("eRekreacija.Services.Database.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_ObjectHoliday", b =>
                {
                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Holiday", "TblHoliday")
                        .WithMany("ObjectHolidays")
                        .HasForeignKey("holiday_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Objects", "TblObjects")
                        .WithMany("ObjectHoliday")
                        .HasForeignKey("object_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblHoliday");

                    b.Navigation("TblObjects");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_ObjectSportCategory", b =>
                {
                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Objects", "TblObject")
                        .WithMany("ObjectSportCategory")
                        .HasForeignKey("object_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_SportCategory", "TblSportcategory")
                        .WithMany("ObjectSportCategories")
                        .HasForeignKey("sport_category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblObject");

                    b.Navigation("TblSportcategory");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Objects", b =>
                {
                    b.HasOne("eRekreacija.Services.Database.ApplicationUser", "User")
                        .WithMany("Objects")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Payment", b =>
                {
                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Appointment", "TblAppointment")
                        .WithOne("TblPayment")
                        .HasForeignKey("eRekreacija.Services.Database.Entities.tbl_Payment", "appointment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Objects", "TblObjects")
                        .WithMany("Payment")
                        .HasForeignKey("object_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eRekreacija.Services.Database.ApplicationUser", "User")
                        .WithMany("Payment")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TblAppointment");

                    b.Navigation("TblObjects");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Review", b =>
                {
                    b.HasOne("eRekreacija.Services.Database.Entities.tbl_Objects", "TblObjects")
                        .WithMany("Reviews")
                        .HasForeignKey("object_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eRekreacija.Services.Database.ApplicationUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TblObjects");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Appointment", b =>
                {
                    b.Navigation("TblPayment")
                        .IsRequired();
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Holiday", b =>
                {
                    b.Navigation("ObjectHolidays");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_Objects", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Favorites");

                    b.Navigation("ObjectHoliday");

                    b.Navigation("ObjectSportCategory");

                    b.Navigation("Payment");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.Entities.tbl_SportCategory", b =>
                {
                    b.Navigation("ObjectSportCategories");
                });

            modelBuilder.Entity("eRekreacija.Services.Database.ApplicationUser", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Favorites");

                    b.Navigation("Notifications");

                    b.Navigation("Objects");

                    b.Navigation("Payment");

                    b.Navigation("RecievedMessage");

                    b.Navigation("Reviews");

                    b.Navigation("SentMessges");
                });
#pragma warning restore 612, 618
        }
    }
}
